POST http://localhost:8082/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRuazJAZ21haWwuY29tIiwiZXhwIjoxNzExNTM0NzY0LCJ1c2VySWQiOjB9.-23w4vg3Svuggl8YR3Jn_8aHplRN_ibghSzkdveYIA4

{
    "name": "Test Authorization",
    "description": "Updated",
    "location": "Updated",
    "dateTime": "2024-03-01T15:30:00.000Z"
}