DELETE  http://localhost:8082/events/3
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRuazNAZ21haWwuY29tIiwiZXhwIjoxNzExNTY0NTE4LCJ1c2VySWQiOjN9.C4JMlrvpo_7zSdlanrVrvElunHgRa39BWH34bF8YlkE