POST http://localhost:8082/events/4/register
content-type: application/json
authorization:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRuazFAZ21haWwuY29tIiwiZXhwIjoxNzExNTY1NTc1LCJ1c2VySWQiOjF9.wHey8yIokFk0OIVQB-6-Xu3eaL2CR8EHrOC0Dc-YP1s